apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: erxi5e52o-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: erxi5e52o-go 
  name: erxi5e52o-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: erxi5e52o-go 
